debug:
security:
  user:
    password: password
  oauth2:
    client:
      accessTokenUri: http://authserver-local:9999/uaa/oauth/token
      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
      clientId: foo
      clientSecret: bar
    resource:
      userInfoUri: http://authserver-local:9999/uaa/user
zuul:
  routes:
    resource:
      path: /resource/**
      url: http://resourceserver-local:9000
    user:
      path: /user/**
      url: http://authserver-local:9999/uaa/user
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG